import React, { useEffect, useState } from 'react';
import { PageHeader } from '../../components/common/PageHeader';
import { Card } from '../../components/common/Card';
import { Button } from '../../components/common/Button';
import { nutritionService } from '../../services/nutritionService';
import { CategoryMetadataDto, FoodItemDto, DietType } from '../../types';
export const NutritionPlanPage: React.FC = () => {
  const [category,setCategory]=useState('Healthy_Normal');
  const [diet,setDiet]=useState<DietType>('VEGETARIAN');
  const [categories,setCategories]=useState<CategoryMetadataDto[]>([]);
  const [foods,setFoods]=useState<FoodItemDto[]>([]);
  const [loading,setLoading]=useState(true); const [error,setError]=useState(false);
  useEffect(()=>{let active=true;setLoading(true);setError(false);Promise.all([nutritionService.getCategories(),nutritionService.getRecommendations(category,diet)]).then(([options,result])=>{if(active){setCategories(options);setFoods(result.recommendedFoods);}}).catch(()=>{if(active)setError(true);}).finally(()=>{if(active)setLoading(false);});return()=>{active=false;};},[category,diet]);
  return <div className="max-w-5xl mx-auto space-y-6"><PageHeader title="Weekly food ideas" subtitle="Seven ideas based on your selected nutrient and dietary preference. This is not a prescribed diet or treatment plan." /><Card className="p-6 space-y-4"><div className="grid sm:grid-cols-2 gap-4"><label className="space-y-2"><span className="block font-semibold">Nutrient focus</span><select className="w-full p-3 rounded-xl border bg-white dark:bg-slate-900" value={category} onChange={e=>setCategory(e.target.value)}>{categories.map(c=><option key={c.code} value={c.code}>{c.displayName}</option>)}</select></label><label className="space-y-2"><span className="block font-semibold">Dietary preference</span><select className="w-full p-3 rounded-xl border bg-white dark:bg-slate-900" value={diet} onChange={e=>setDiet(e.target.value as DietType)}><option value="VEGETARIAN">Vegetarian</option><option value="VEGAN">Vegan</option><option value="NON_VEGETARIAN">Non-vegetarian</option></select></label></div><p className="text-sm text-slate-500">Add suitable options to balanced meals. Check allergies and product labels. Needs vary with age and health conditions; a dietitian can help create a complete plan. Repeated foods reflect the available catalogue.</p></Card>{loading ? <p role="status">Loading matching foods...</p> : error ? <p role="alert">Food guidance could not be loaded. Please change the selection or try again later.</p> : !foods.length ? <p>No matching foods are available for this combination. Try a different nutrient or dietary preference.</p> : <Card className="p-6 overflow-x-auto"><table className="w-full text-left text-sm"><caption className="text-left font-bold mb-4">Your seven-day food ideas</caption><thead><tr><th className="p-3">Day</th><th>Food idea</th><th>Serving information</th></tr></thead><tbody>{Array.from({length:7},(_,i)=>{const food=foods[i%foods.length];return <tr key={i} className="border-t border-slate-200 dark:border-slate-800"><td className="p-3 whitespace-nowrap">Day {i+1}</td><td className="pr-4">{food.foodName}</td><td>{food.servingSuggestion || 'Include as part of a balanced meal if suitable for you.'}</td></tr>;})}</tbody></table><Button className="mt-5 print:hidden" onClick={()=>window.print()}>Print food ideas</Button></Card>}</div>;
};
