@echo off
set MYSQL="C:\Program Files\MySQL\MySQL Server 8.0\bin\mysql.exe"
echo 1. Creating schema...
%MYSQL% -u root -proot < database\schema.sql
echo 2. Seeding symptoms...
%MYSQL% -u root -proot nutrivision_db < database\seed_symptoms.sql
echo 3. Seeding nutrition matrix...
%MYSQL% -u root -proot nutrivision_db < database\seed_nutrition.sql
echo 4. Verifying database...
%MYSQL% -u root -proot -e "USE nutrivision_db; SHOW TABLES; SELECT COUNT(*) AS symptom_count FROM symptoms; SELECT COUNT(*) AS food_rec_count FROM food_recommendations;"
echo Initialization complete!
