import React from 'react';
import { AlertOctagon, ShieldAlert, CheckCircle, Stethoscope, AlertTriangle } from 'lucide-react';
import { PageHeader } from '../components/common/PageHeader';
import { Card } from '../components/common/Card';

export const DisclaimerPage: React.FC = () => {
  return (
    <div className="space-y-10 py-8 max-w-4xl mx-auto px-4 sm:px-6 lg:px-8">
      <PageHeader
        title="Comprehensive Medical & AI Safety Disclaimer"
        subtitle="Please read this document carefully to understand the non-diagnostic nature and scope of NutriVision AI."
      />

      {/* Main Notice Card */}
      <div className="p-6 rounded-2xl bg-amber-500/10 dark:bg-amber-500/15 border-2 border-amber-500/30 text-slate-900 dark:text-slate-100 space-y-3">
        <div className="flex items-center gap-2.5 text-amber-800 dark:text-amber-300 font-bold text-lg">
          <AlertOctagon className="w-6 h-6 text-amber-600 dark:text-amber-400" />
          <span>Non-Diagnostic Educational Prototype Notice</span>
        </div>
        <p className="text-sm sm:text-base leading-relaxed text-slate-800 dark:text-slate-200">
          <strong>NutriVision AI is an educational college prototype and research demonstration system.</strong> It is NOT a medically certified diagnostic device, is NOT approved by any medical regulatory body (such as FDA or CDSCO), and must NEVER be used as a substitute for professional clinical medical advice, diagnostic testing, or treatment.
        </p>
      </div>

      {/* Structured Sections */}
      <div className="space-y-6">
        <Card variant="default" className="p-6 space-y-3">
          <h3 className="text-lg font-bold text-slate-900 dark:text-slate-100 flex items-center gap-2">
            <Stethoscope className="w-5 h-5 text-health-600 dark:text-health-400" />
            1. No Medical Relationship or Clinical Guarantee
          </h3>
          <p className="text-sm text-slate-600 dark:text-slate-400 leading-relaxed">
            Interactions with this web application, including image uploads, symptom questionnaires, and dietary recommendations, do not establish a doctor-patient relationship. The outputs generated by NutriVision AI are preliminary indicators or probabilistic associations derived from computer vision patterns.
          </p>
        </Card>

        <Card variant="default" className="p-6 space-y-3">
          <h3 className="text-lg font-bold text-slate-900 dark:text-slate-100 flex items-center gap-2">
            <ShieldAlert className="w-5 h-5 text-health-600 dark:text-health-400" />
            2. Meaning of "Model Confidence"
          </h3>
          <p className="text-sm text-slate-600 dark:text-slate-400 leading-relaxed">
            All percentage values generated by this system represent internal statistical <strong>Model Confidence</strong> scores (e.g., Softmax layer distribution values), reflecting the similarity of your photograph and symptoms to our training dataset samples. <strong>Model Confidence is NOT diagnostic accuracy or clinical certainty.</strong> High confidence does not prove a deficiency, and low confidence does not guarantee normal health.
          </p>
        </Card>

        <Card variant="default" className="p-6 space-y-3">
          <h3 className="text-lg font-bold text-slate-900 dark:text-slate-100 flex items-center gap-2">
            <AlertTriangle className="w-5 h-5 text-health-600 dark:text-health-400" />
            3. Inherent Technical & Image Limitations
          </h3>
          <ul className="list-disc pl-5 space-y-2 text-sm text-slate-600 dark:text-slate-400 leading-relaxed">
            <li><strong>Lighting & Camera Artifacts:</strong> Variations in smartphone sensors, color temperature, and flash can distort subtle anatomical features like conjunctival pallor or skin tone.</li>
            <li><strong>Symptom Ambiguity:</strong> Many symptoms (e.g. fatigue, hair thinning, xerosis) are non-specific and occur across a broad variety of medical conditions unrelated to vitamin deficiencies.</li>
            <li><strong>Dataset Limitations:</strong> Models trained on prototype datasets may exhibit performance disparities across diverse skin tones (Fitzpatrick scales I–VI) and age demographics.</li>
          </ul>
        </Card>

        <Card variant="default" className="p-6 space-y-3">
          <h3 className="text-lg font-bold text-slate-900 dark:text-slate-100 flex items-center gap-2">
            <CheckCircle className="w-5 h-5 text-health-600 dark:text-health-400" />
            4. When You Should Seek Immediate Medical Attention
          </h3>
          <p className="text-sm text-slate-600 dark:text-slate-400 leading-relaxed">
            If you are experiencing severe, sudden, or debilitating symptoms—such as acute shortness of breath, unexplained fainting, severe visual disturbances, rapid hair loss with lesions, or severe chest discomfort—do not use this application. Please seek urgent care at the nearest hospital or emergency clinic immediately.
          </p>
        </Card>
      </div>
    </div>
  );
};
