import React from 'react';
import { Link, useSearchParams } from 'react-router-dom';
import { ArrowUpRight, ArrowRight, Camera, BookOpen, History, Leaf, Check } from 'lucide-react';

export const designDirections = [
  { id: 'sage', name: 'Sage Journal', description: 'Warm ivory, botanical forms and editorial serif typography.', label: 'Calm & considered' },
  { id: 'blue', name: 'Blue Studio', description: 'Crisp blue, a centred composition and modern sans-serif typography.', label: 'Clear & structured' },
  { id: 'clay', name: 'Warm Terracotta', description: 'Earthy tones, an asymmetric layout and a warm magazine feel.', label: 'Warm & personal' },
];
export const BotanicalArt = () => <svg viewBox="0 0 400 360" fill="none" aria-hidden="true" className="botanical-art"><ellipse cx="200" cy="322" rx="113" ry="12" fill="currentColor" opacity=".08"/><path d="M192 300C192 234 211 171 251 80M192 259C159 217 138 186 119 141M204 204C247 181 280 147 296 113" stroke="currentColor" strokeWidth="3" strokeLinecap="round"/><path d="M217 156C184 122 197 71 260 42C273 95 256 137 217 156Z" fill="currentColor" opacity=".78"/><path d="M186 239C124 245 80 203 89 147C147 149 181 182 186 239Z" fill="currentColor" opacity=".5"/><path d="M206 202C219 146 263 126 319 137C300 191 261 214 206 202Z" fill="currentColor" opacity=".9"/><path d="M242 108L218 155M118 178L178 229M229 188L292 154" stroke="var(--design-paper)" strokeWidth="1.4" opacity=".8"/><circle cx="111" cy="86" r="21" stroke="currentColor" opacity=".2"/><circle cx="309" cy="249" r="7" fill="currentColor" opacity=".2"/></svg>;

export const LandingPage: React.FC = () => {
  const [search] = useSearchParams();
  const variant = designDirections.find(d => d.id === search.get('design'))?.id || 'sage';
  return <div className={`wellness-home direction-${variant}`}>
    {search.has('design') && <div className="design-preview-bar"><Link to="/designs">← All design variants</Link><span>{designDirections.find(d => d.id === variant)?.name} · Preview</span></div>}
    <section className="wellness-hero"><div className="hero-copy"><p className="eyebrow"><span/> YOUR EVERYDAY WELLBEING, CONSIDERED.</p><h1>A little clarity.<br/>A healthier <em>perspective.</em></h1><p className="hero-description">A calm space to record your concerns, understand everyday nutrition, and take your next step with confidence.</p><div className="hero-actions"><Link to="/assessment/new" className="wellness-button">Start your photo check <ArrowUpRight size={19}/></Link><Link to="/how-it-works" className="wellness-text-link">Explore how it works <ArrowRight size={17}/></Link></div><p className="hero-note">Photo & symptom records. Nutrition education.<br/>Support for your wellbeing — not a medical diagnosis.</p></div>
    <div className="hero-visual"><div className="visual-caption"><Leaf size={17}/><span>Small steps. Thoughtful care.</span><span className="visual-edition">01 / WELLBEING</span></div><BotanicalArt/><div className="journal-card"><span className="journal-icon"><Camera size={21}/></span><div><strong>Begin with a clearer picture</strong><p>One photo. Your own observations.</p></div><ArrowUpRight size={18}/></div><div className="visual-footnote"><span>GROW YOUR UNDERSTANDING</span><span>At your own pace</span></div></div></section>
    <section className="wellness-path" aria-label="Your next steps"><div className="path-intro"><p className="eyebrow">A SIMPLE PLACE TO START</p><h2>More understanding.<br/><em>Less overwhelm.</em></h2></div>{[
      {n:'01',icon:Camera,title:'Check your photo',text:'Upload a close-up and check that it is clear and shows the right body area.',link:'/assessment/new'},
      {n:'02',icon:BookOpen,title:'Explore nutrition',text:'Get to know vitamins and food sources that fit your dietary preferences.',link:'/recommendations'},
      {n:'03',icon:History,title:'Keep your story',text:'Save your observations and bring a useful record to your next consultation.',link:'/history'},
    ].map(({n,icon:Icon,title,text,link})=><Link key={n} to={link} className="path-item"><div className="path-top"><Icon size={22}/><span>{n}</span></div><h3>{title}</h3><p>{text}</p><ArrowUpRight size={19} className="path-arrow"/></Link>)}</section>
    <section className="care-note"><div><p className="eyebrow">CLEAR ABOUT WHAT WE CAN DO</p><h2>A useful record.<br/>An informed conversation.</h2></div><div><p>Photos can help you document a concern. They cannot establish your vitamin levels. This platform checks photo suitability and helps you organise your observations.</p><p className="care-check"><Check size={18}/> For diagnosis and testing, speak with a qualified clinician.</p><Link to="/doctors" className="wellness-text-link">Find professional care <ArrowUpRight size={17}/></Link></div></section>
  </div>;
};

export const DesignVariantsPage = () => <div className="design-gallery"><p className="eyebrow">THREE DIRECTIONS. ONE PURPOSE.</p><h1>A calmer way forward.</h1><p className="gallery-description">Explore three visual directions for Vitamin Deficiency. Sage Journal is the selected design for the main platform.</p><div className="design-options">{designDirections.map((design,i)=><Link key={design.id} to={`/?design=${design.id}`} className={`design-option direction-${design.id}`}><div className="design-sample"><span>0{i+1} / {design.label}</span><h2>{design.name}</h2><BotanicalArt/></div><div className="design-option-details"><h3>{design.name}{i===0&&<small>Selected</small>}</h3><p>{design.description}</p><span>Explore this direction <ArrowUpRight size={18}/></span></div></Link>)}</div><Link className="wellness-text-link" to="/">Back to the main website <ArrowRight size={18}/></Link></div>;
